### ISSUE TITLE
Always no results on next page

### ISSUE THREAD

**Issue by Hoculus** [opsdisk/yagooglesearch#11]
First of all, thanks for the great tool, anyway it seems it fails to perform the search for any 2nd page:  "No valid search results found on this page.  Moving on..."

**Comment by opsdisk** [comment]
Hi @Hoculus - thanks for submitting an issue.

* Can you provide some more details around the issue like the exact search term?
* What switches/options are you using?
* What version of python and yagooglesearch are you using?
* Any debug output / screen shots?

**Comment by Hoculus** [comment]
query = "inurl:xxx/xxxxx"
`client = yagooglesearch.SearchClient(
    query,
    lang="it",
    verbosity=4,
    tbs="li:1",
    proxy=PROXY,
    verify_ssl=False,
    num=10,
    max_search_result_urls_to_return=100,
    minimum_delay_between_paged_results_in_seconds=3,
    yagooglesearch_manages_http_429s=False,  # Add to manage HTTP 429s.
)`

I've tried a bunch of settings anyway but same issue output:

`No valid search results found on this page.  Moving on...`

and stops

**Comment by opsdisk** [comment]
Thanks @Hoculus 

FYI, any URLs with `google.com` in it are thrown out, so in case your query has it, that would be why.

It's possible there isn't another page.  Currently, the logic to determine that hasn't been implemented (the HTML class names are randomized, so it's hard to pick out with the BeautifulSoup HTML parser) so it has to browse to a page and determine there are no results. 

When you run it, there should be a `Requesting URL:` INFO line near the beginning of the output (see screenshot below).

For example...within an ipython shell...

```python
import yagooglesearch

query = "site:github.com"

client = yagooglesearch.SearchClient(
    query,
    lang="it",
    verbosity=4,
    tbs="li:1",
    verify_ssl=False,
    num=10,
    max_search_result_urls_to_return=100,
    minimum_delay_between_paged_results_in_seconds=3,
    yagooglesearch_manages_http_429s=False,
)
client.assign_random_user_agent()

urls = client.search()

len(urls)
```

![image](https://user-images.githubusercontent.com/8660252/153777146-2ef8955c-c6f8-4677-afa3-6ad7a95522df.png)

If you browse to that link in a browser and scroll to the bottom, does it show a "2" or "Avanti" signifying another page of search results?

![image](https://user-images.githubusercontent.com/8660252/153777246-16e03e4e-2ce8-49e0-9f0b-c1ab6ef45c33.png)

**Comment by opsdisk** [comment]
Yeah, that is odd.  There was an issue (https://github.com/opsdisk/yagooglesearch/issues/5) a few months back about Google not liking traffic sourcing from EU countries, which yagooglesearch detects ("Looks like your IP address is sourcing from a European Union location").  Would be curious if you got the same results sourcing your IP from a non-EU country?

One thing that comes to mind is that this value (https://github.com/opsdisk/yagooglesearch/blob/master/yagooglesearch/__init__.py#L361) is no longer "valid" for paged Google searches.  I grabbed it from a browser a few months back.  You'll notice there's a date and country code ("fr") that worked at the time.  You could try swapping that with what is found in your browser (using your browser's DevTools) when you browse to google.com and have to "Accept" their search terms.

Anecdotally, I've seen my own search results vary across different searches and I don't know why.  I chalk it up to Google not being as consistent as I'd hope.

One last thing, you mind letting me know what version you're running?  It's the `__version__` string found in `__init__.py`

https://github.com/opsdisk/yagooglesearch/blob/master/yagooglesearch/__init__.py#L15

**Comment by Hoculus** [comment]
I'll try asap using non EU proxy.. meanwhile here's the cookie payload when the cookie banner is in Italian

`consentCookiePayload='YES+shp.gws-20220209-0-RC2.it+FX+020'`

changing language in the banner leads to a different payload with the country code in the string itself so maybe the solution could be swapping the language always to the known one.

Here's the version I'm using right now: 

`__version__ = "1.6.0"`

**Comment by opsdisk** [comment]
Good to see that the version is the most recent.

If you're comfortable doing it, you could modify the cookie [here](https://github.com/opsdisk/yagooglesearch/blob/master/yagooglesearch/__init__.py#L361) and see if that helps.  If you're using a virtual environment, it will be in a path similar to `.venv/lib/python3.7/site-packages/yagooglesearch-1.6.0-py3.7.egg/yagooglesearch/__init__.py`

I'm doubtful, but If that does the trick, I'll look at modifying it on the fly.

**Comment by opsdisk** [comment]
Hi @Hoculus - any updates with this?

**Comment by Hoculus** [comment]
Hi @opsdisk, it actually solved the problem! thanks.

**Comment by truskk** [comment]
how exactly did you fix the issue? Ive tried changing the consent cookie country code and it still doesn't work

**Comment by opsdisk** [comment]
Hey @truskk - you mind opening a new issue with some more details of what you're trying to do and the results you're seeing?
