### ISSUE TITLE
use paid proxy and get error while tunneling

### ISSUE THREAD

**Issue by tjengbudi** [opsdisk/yagooglesearch#18]
hello,
i want to ask about some question about proxy, i have a paid proxy that used authentication
i trying with pure "requests" in blank project to fetch google and it works fine. but after i added it at yagooglesearch it have error like this
`Traceback (most recent call last):
  File "C:\Users\budi\.virtualenvs\article-30Om8FEk\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\budi\.virtualenvs\article-30Om8FEk\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\budi\.virtualenvs\article-30Om8FEk\lib\site-packages\urllib3\connection.py", line 369, in connect
    self._tunnel()
  File "C:\Users\budi\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 924, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 407 Proxy Authentication Required`

i check several time and it can used in pure requests code. 
is there any clue for this?

**Comment by opsdisk** [comment]
Take a look at https://requests.readthedocs.io/en/latest/user/advanced/#proxies

You can...

1) set proxy using this format when instantiating the class `proxy=http://user:password@host:port`

2) hardcode it in the library here: https://github.com/opsdisk/yagooglesearch/blob/master/yagooglesearch/__init__.py#L183

3) or trying wrapping it with `proxychains4` - https://github.com/opsdisk/pagodo#proxychains4-support

**Comment by opsdisk** [comment]
@tjengbudi Without access to the paid proxy, it's hard for me to assist in troubleshooting this.  I never got a response from you in our Twitter DM discussion.  I'll keep this issue open a bit longer.

**Comment by opsdisk** [comment]
Closing this issue out @tjengbudi. If you have additional or new information, we can reopen this one.
