### ISSUE TITLE
Add Language Support for Search Results

### ISSUE THREAD

**Issue by jboarman** [opsdisk/yagooglesearch#25]
The current `hl` language option refers to the language of the _HTML_ UI.  However, to search for _results_ in a particular language, the `lr` parameter must be set.

Please add support for both language options:

* `hl` => HTML Language (UI)
* `lr` => Language of Results (Linked Content)

![image](https://github.com/opsdisk/yagooglesearch/assets/1108065/d53b05fa-ae2e-4ccd-87dd-881443e4b16f)

For references, the enumeration of supported languages for results are as follows:

```
lang_af=Afrikaans
lang_ar=Arabic
lang_hy=Armenian
lang_be=Belarusian
lang_bg=Bulgarian
lang_ca=Catalan
lang_zh-CN=Chinese (Simplified)
lang_zh-TW=Chinese (Traditional)
lang_hr=Croatian
lang_cs=Czech
lang_da=Danish
lang_nl=Dutch
lang_en=English
lang_eo=Esperanto
lang_et=Estonian
lang_tl=Filipino
lang_fi=Finnish
lang_fr=French
lang_de=German
lang_el=Greek
lang_iw=Hebrew
lang_hi=Hindi
lang_hu=Hungarian
lang_is=Icelandic
lang_id=Indonesian
lang_it=Italian
lang_ja=Japanese
lang_ko=Korean
lang_lv=Latvian
lang_lt=Lithuanian
lang_no=Norwegian
lang_fa=Persian
lang_pl=Polish
lang_pt=Portuguese
lang_ro=Romanian
lang_ru=Russian
lang_sr=Serbian
lang_sk=Slovak
lang_sl=Slovenian
lang_es=Spanish
lang_sw=Swahili
lang_sv=Swedish
lang_th=Thai
lang_tr=Turkish
lang_uk=Ukrainian
lang_vi=Vietnamese
```

**Comment by opsdisk** [comment]
Thanks for taking the time to submit an issue @jboarman - might be a few days before I can take a look.

**Comment by opsdisk** [comment]
@jboarman take a look at https://github.com/opsdisk/yagooglesearch/pull/30
