### ISSUE TITLE
extra_params={"uule": f'{uule}'},

### ISSUE THREAD

**Issue by camingout** [opsdisk/yagooglesearch#29]
uule = "w+CAIQICIiV2Fyc2F3LE1hc292aWFuIFZvaXZvZGVzaGlwLFBvbGFuZA" 
but in url we have
&uule=w%2BCAIQICIiV2Fyc2F3LE1hc292aWFuIFZvaXZvZGVzaGlwLFBvbGFuZA
simbol "+" is "%2B" but it's not correct

**Comment by opsdisk** [comment]
Thanks for putting in an issue @camingout Looks like it's URL encoding, which you do not want for the adhoc `uule` parameter you're adding?

For the time being, you can try and comment out this line https://github.com/opsdisk/yagooglesearch/blob/master/yagooglesearch/__init__.py#L464 which won't convert the `+` to a `%2B`

uule reference: https://valentin.app/uule.html

**Comment by opsdisk** [comment]
I removed any URL encoding of `extra_params` in https://github.com/opsdisk/yagooglesearch/pull/30
