### ISSUE TITLE
result_languages.txt file is not being included in setuptools package_data

### ISSUE THREAD

**Issue by pguridi** [opsdisk/yagooglesearch#37]
the file `result_languages.txt` is not being installed with the package, resulting in this print statement everytime the library is loaded:

```There was an issue loading the result languages file.  Exception: [Errno 2] No such file or directory: '/Users/nippur/src/linkedin-scraper/venv/lib/python3.11/site-packages/yagooglesearch/result_languages.txt'```

**Comment by opsdisk** [comment]
Thanks for submitting an issue @pguridi - give me a few days to take a look at it.
